# Generated by Django 2.1.1 on 2019-09-07 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=255)),
                ('img', models.ImageField(upload_to='images/')),
                ('is_worthy', models.BooleanField(default=None)),
            ],
        ),
    ]
