# Generated by Django 2.1.1 on 2019-09-08 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grabit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='is_worthy',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_worthy',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
